steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_IMAGE_TAG", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE_TAG"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "$_IMAGE_TAG",
        "--platform",
        "managed",
        "--region",
        "$_REGION",
        "--allow-unauthenticated",
      ]
substitutions:
  _IMAGE_TAG: europe-west1-docker.pkg.dev/emre-aksoy/docker/sharex-uploader
  _SERVICE_NAME: sharex-uploader
  _REGION: europe-west1
